export const SET_APIKEY = 'SET_APIKEY';
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
export const LOAD_FORMS = 'LOAD_FORMS';
export const SELECT_FORM = 'SELECT_FORM';
export const SET_CONTENT_LOADING = 'SET_CONTENT_LOADING';
export const SET_CHART_BACKGROUND_COLOR = 'SET_CHART_BACKGROUND_COLOR';
export const SET_CHART_BACKGROUND_COLORS = 'SET_CHART_BACKGROUND_COLORS';
